# Cloudflare Pages configuration
name = "cosmicagenda"

[build]
command = "npm run build:cloudflare"

[build.environment]
NODE_VERSION = "18.17.1"
NPM_VERSION = "10.8.3"

[site]
bucket = "./dist"

[env.production]
pages_build_output_dir = "dist"
